
version: 2

models:
  - name: stg_keywords__ad_group
    description: "Google Ads keywords ad group raw table with renamed metric and dimensions"
    columns:
      - name: segments_date
        description: "The date column"
        tests:
          - not_null
      - name: ad_group_id
        description: "The ad_group_id column"
        tests:
          - not_null
      - name: ad_group_name
        description: "The ad_group_name column"
        tests:
          - not_null
      - name: ad_group_status
        description: "The ad_group_status column"
      - name: ad_group_type
        description: "The ad_group_type column"
     

  - name: stg_keywords__campaign
    description: "Google Ads keywords campaign raw table with renamed metric and dimensions"
    columns:
      - name: segments_date
        description: "The date column"
        tests:
          - not_null
      - name: campaign_name
        description: "The campaign_name column"
        tests:
          - not_null
      - name: campaign_id
        description: "The campaign_id column"
        tests:
          - not_null
      - name: campaign_status
        description: "The campaign_status column"
        tests:
          - not_null


  - name: stg_keywords__keyword
    description: "Google Ads keywords keyword raw table with renamed metric and dimensions"
    columns:
      - name: segments_date
        description: "The date column"
        tests:
          - not_null
      - name: ad_group_criterion_criterion_id
        description: "The ad_group_criterion_criterion_id column"
        tests:
          - not_null
      - name: campaign_id
        description: "The campaign_id column"
        tests:
          - not_null
      - name: ad_group_id
        description: "The ad_group_id column"
        tests:
          - not_null
      - name: ad_group_criterion_keyword_text
        description: "The ad_group_criterion_keyword_text column"
      - name: ad_group_criterion_keyword_match_type
        description: "The ad_group_criterion_keyword_match_type column"
      - name: clicks
        description: "The clicks column"
        tests:
          - not_null
      - name: impressions
        description: "The impressions column"
        tests:
          - not_null
      - name: ctr
        description: "The ctr column"
        tests:
          - not_null
      - name: cost_micros
        description: "The cost_micros column"
        tests:
          - not_null
      - name: cost
        description: "The cost column"
        tests:
          - not_null

  - name: stg_keywords__ad_group_criterion
    description: "Google Ads keywords ad_group_criterion raw table to look up status of keyword (removed, enabled, paused etc)"
    columns:
      - name: ad_group_id
        description: "The ad_group_id column"
        tests:
          - not_null
      - name: ad_group_criterion_criterion_id
        description: "The ad_group_id column"
        tests:
          - not_null
      - name: ad_group_criterion_keyword_text
        description: "The ad_group_criterion_keyword_text column"
      - name: ad_group_criterion_status
        description: "The ad_group_criterion_status column"