
version: 2

models:
  - name: stg_gads__ad_group_ad_legacy
    description: "Google Ads ad group ad legacy raw table with renamed metric and dimensions"
    columns:
      - name: segments_date
        description: "The date column"
        tests:
          - not_null
      - name: customer_id
        description: "The customer_id column"
        tests:
          - not_null
      - name: campaign_id
        description: "The campaign_id column"
        tests:
          - not_null
      - name: campaign_name
        description: "The campaign_name column"
        tests:
          - not_null
      - name: campaign_status
        description: "The campaign_status column"
        tests:
          - not_null
      - name: campaign_type
        description: "The campaign_type column"
        tests:
          - not_null
      - name: ad_group_id
        description: "The ad_group_id column"
        tests:
          - not_null
      - name: ad_group_name
        description: "The ad_group_name column"
        tests:
          - not_null
      - name: ad_group_ad_id
        description: "The ad_group_ad_id column"
        tests:
          - not_null
      - name: ad_group_ad_status
        description: "The ad_group_ad_status column"
      - name: ad_group_status
        description: "The ad_group_status column"
      - name: ad_group_ad_type
        description: "The ad_group_ad_type column"
      - name: ad_group_ad_strength
        description: "The ad_group_ad_strength column"
      - name: ad_group_ad_final_urls
        description: "The ad_group_ad_final_urls column"
      - name: clicks
        description: "The clicks column"
        tests:
          - not_null
      - name: impressions
        description: "The impressions column"
        tests:
          - not_null
      - name: conversions
        description: "The conversions column"
        tests:
          - not_null
      - name: interactions
        description: "The interactions column"
        tests:
          - not_null
      - name: ctr
        description: "The ctr column"
        tests:
          - not_null
      - name: avg_cpc
        description: "The avg_cpc column"
        tests:
          - not_null
      - name: cost_micros
        description: "The cost_micros column"
        tests:
          - not_null

  - name: stg_gads__ad_group_ad
    description: "Google Ads ad group ad raw table with renamed metric and dimensions"
    columns:
      - name: segments_date
        description: "The date column"
        tests:
          - not_null
      - name: ad_group_id
        description: "The ad_group_id column"
        tests:
          - not_null
      - name: ad_group_ad_id
        description: "The ad_group_ad_id column"
        tests:
          - not_null
      - name: ad_group_ad_status
        description: "The ad_group_ad_status column"
      - name: ad_group_status
        description: "The ad_group_status column"
      - name: ad_group_ad_type
        description: "The ad_group_ad_type column"
      - name: ad_group_ad_strength
        description: "The ad_group_ad_strength column"
      - name: ad_group_ad_final_urls
        description: "The ad_group_ad_final_urls column"
      - name: ad_group_ad_ad_responsive_search_ad_headlines
        description: "The ad_group_ad_ad_responsive_search_ad_headlines column"
      - name: ad_group_ad_expanded_text_ad_headline_part1
        description: "The ad_group_ad_expanded_text_ad_headline_part1 column"
      - name: ad_group_ad_expanded_text_ad_headline_part2
        description: "The ad_group_ad_expanded_text_ad_headline_part2 column"
      - name: ad_group_ad_expanded_text_ad_headline_part3
        description: "The ad_group_ad_expanded_text_ad_headline_part3 column"
      - name: ad_group_ad_expanded_text_ad_description
        description: "The ad_group_ad_expanded_text_ad_description column"
      - name: ad_group_ad_expanded_text_ad_description2
        description: "The ad_group_ad_expanded_text_ad_description2 column"
      - name: ad_group_ad_policy_summary_approval_status
        description: "The ad_group_ad_policy_summary_approval_status column"

  - name: stg_gads__ad_group
    description: "Google Ads ad group raw table with renamed metric and dimensions"
    columns:
      - name: segments_date
        description: "The date column"
        tests:
          - not_null
      - name: ad_group_id
        description: "The ad_group_id column"
        tests:
          - not_null
      - name: ad_group_name
        description: "The ad_group_name column"
        tests:
          - not_null
      - name: campaign_id
        description: "The campaign_id column"
        tests:
          - not_null
      - name: ad_group_status
        description: "The ad_group_status column"
      - name: ad_group_type
        description: "The ad_group_type column"

  - name: stg_gads__campaign
    description: "Google Ads ad group raw table with renamed metric and dimensions"
    columns:
      - name: segments_date
        description: "The date column"
        tests:
          - not_null
      - name: campaign_name
        description: "The campaign_name column"
        tests:
          - not_null
      - name: campaign_id
        description: "The campaign_id column"
        tests:
          - not_null
      - name: campaign_status
        description: "The campaign_status column"
        tests:
          - not_null
      - name: campaign_optimization_score
        description: "The campaign_optimization_score column"
      - name: campaign_advertising_channel_type
        description: "The campaign_advertising_channel_type column"
      - name: campaign_bidding_strategy
        description: "The campaign_bidding_strategy column"
      - name: campaign_bidding_strategy_type
        description: "The campaign_bidding_strategy_type column"
      - name: campaign_budget_amount_micros
        description: "The campaign_budget_amount_micros column"
        tests:
          - not_null
      - name: clicks
        description: "The clicks column"
        tests:
          - not_null
      - name: impressions
        description: "The impressions column"
        tests:
          - not_null
      - name: ctr
        description: "The ctr column"
        tests:
          - not_null
      - name: avg_cpc
        description: "The avg_cpc column"
        tests:
          - not_null
      - name: cost_micros
        description: "The cost_micros column"
        tests:
          - not_null