version: '3.8'
services:
  db:
    image: postgres:latest
    shm_size: 1gb
    restart: unless-stopped
    env_file:
      .env
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  my_dbdata:
